# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ayoub
  password: Casanegra1997
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: bluelry_api_development
test:
  <<: *default
  database: bluelry_api_test

production:
  <<: *default
  database: dbbluelry
  username: ayoub
  password: Casanegra1997
  host: dbbluelry.c1ug8s2coknc.eu-west-3.rds.amazonaws.com
  port: 3306
